apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=./Dockerfile",
          "--context=gs://cloudsolver-334113.appspot.com/solvers/IMAGE_TAG.tar.gz",
          "--destination=europe-docker.pkg.dev/cloudsolver-334113/solverservice/IMAGE_TAG"] # replace with your dockerhub account
    volumeMounts:
    - name: keys
      mountPath: /keys
      readOnly: true
  restartPolicy: Never
  volumes:
    - name: keys
      secret:
        secretName: google-api-key