services:
  react:
    container_name: react
    image: react-frontend
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes: 
      - ./src:/app/src
    ports: 
      - 3000:3000
    networks:
      - cloudsolver

networks:
  cloudsolver:
    external: true
