apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: europe-west1-docker.pkg.dev/cloudsolver-334113/backend/express:${GITHUB_SHA}
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: keys
          mountPath: /keys
          readOnly: true
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/keys/google-api-key.json"
          - name: EXPRESS_ALLOW_ORIGIN
            value: "https://cloudsolver.xyz"
          - name: NODE_ENV
            value: "prod"
          - name: EXPRESS_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: express-cookie-secret
                key: secret
      volumes:
      - name: keys
        secret:
          secretName: google-api-key

