apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudsolver-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cloudsolver-static-ip
    networking.gke.io/managed-certificates: cloudsolver-managed-cert
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/v1beta1.FrontendConfig: https-redirect-config
spec:
  rules:
  - host: cloudsolver.info
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: react-service
            port:
              number: 3000
  - host: api.cloudsolver.info
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: express-service
            port:
              number: 3000
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: https-redirect-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
