apiVersion: v1
kind: Service
metadata:
  name: express-service
  annotations:
    cloud.google.com/backend-config: '{"default": "cloudsolver-backend-config"}'
spec:
  ports:
  - protocol: TCP
    port: 3000  
    targetPort: 3000
  selector:
    app: express
  type: NodePort
