#!/usr/bin/env bash
CONFIG=${1?Error: Include Solver Config}
SOLVERREQ=${2?Error: Include the files which the solver needs, a folder with e.g: mznlib & executable}
if [[ $CONFIG != *.msc  ]]; then
	echo "not a Config"
	exit 1
fi
#if [[ ! -d $SOLVERREQ ]]; then
#	echo "not a Libary Folder"
#	exit 5
#fi
gsutil cp $CONFIG gs://dm885-cloud-solver.appspot.com/Solvers
gsutil cp -r $SOLVERREQ gs://dm885-cloud-solver.appspot.com/Solvers
