apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: europe-north1-docker.pkg.dev/cloudsolver-334113/frontend/react:latest #${GITHUB_SHA}
        ports:
        - containerPort: 3000