apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=./Dockerfile",
          "--context=dir:/workspace/",
          "--destination=<europe-docker.pkg.dev/cloudsolver-334113/solverservice/$IMAGE:$TAG>"]
    volumeMounts:
    - name: keys
      mountPath: /keys
      readOnly: true
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/keys/google-api-key.json"
  restartPolicy: Never
  volumes:
    - name: keys
      secret:
        secretName: google-api-key