name: CI - Backend
on:
  push:
    branches-ignore: [ main ]
    paths: [ backend/** ]

jobs:
  integration:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [ 16.13.0 ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node - backend
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
        
    - name: Install dependencies - backend
      working-directory: ./backend
      run: npm ci --silent
    
    - name: Run tests - backend
      working-directory: backend
      run: npm run test