name: CI - Frontend
on:
  push:
    branches-ignore: [ main ]
    paths: [ frontend/** ]

jobs:
  integration:
    runs-on: ubuntu-latest
    environment: productionS

    strategy:
      matrix:
        node-version: [ 16.13.0 ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node - frontend
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
        
    - name: Install dependencies - frontend
      working-directory: ./frontend
      run: npm ci --silent
    
    - name: Run tests - frontend
      working-directory: frontend
      run: npm run test