name: CI
on:
  push:
    branches-ignore:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [ 16.13.0 ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Check which folder
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'

    - name: Setup Node
      if: steps.filter.outputs.backend == 'true'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
        
    - name: Install dependencies
      if: steps.filter.outputs.backend == 'true'
      working-directory: ./backend
      run: npm ci --silent
    
    - name: Run Tests
      if: steps.filter.outputs.backend == 'true'
      working-directory: ./backend
      run: npm run test

    #   - name: Setup Node
    #   if: steps.filter.outputs.frontend == 'true'
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    #     cache-dependency-path: './frontend/package-lock.json'
        
    # - name: Install dependencies
    #   if: steps.filter.outputs.frontend == 'true'
    #   working-directory: ./frontend
    #   run: npm ci --silent
    
    # - name: Run Tests
    #   if: steps.filter.outputs.frontend == 'true'
    #   working-directory: ./frontend
    #   run: npm run test