name: CI
on:
  push:
    branches-ignore: [ main ]
    paths: [ backend, frontend ]

jobs:
  integration:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [ 16.13.0 ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Check which folder
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'

# ----------------- BACKEND -----------------------------
    # if: steps.filter.outputs.backend == 'true'
    - name: cd folder
      run: cd backend && ls && echo github.actions_path
    
    - name: Setup Node - backend
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies - backend
      run: npm ci --silent
    
    - name: Run tests - backend
      run: npm run test

# ----------------- FRONTEND -----------------------------
    # if: steps.filter.outputs.frontend == 'true'
    - name: Setup Node - frontend
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
        
    - name: Install dependencies - frontend
      working-directory: ./frontend
      run: npm ci --silent
    
    - name: Run tests - frontend
      working-directory: ./frontend
      run: npm run test
