name: CI
on:
  push:
    branches-ignore:
      - main
    
jobs:
  integration-backend:
    runs-on: ubuntu-latest
    environment: production
    working-directory: ./backend

    strategy:
      matrix:
        node-version: [ 16.13.0 ]
    
    steps:
     - name: Checkout
       uses: actions/checkout@v2
    
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
        
     - name: Install dependencies
       run: npm ci --silent
     
     - name: Run Tests
       run: npm run test

integration-frontend:
    runs-on: ubuntu-latest
    environment: production
    working-directory: ./frontend

    strategy:
      matrix:
        node-version: [ 16.13.0 ]
    
    steps:
     - name: Checkout
       uses: actions/checkout@v2
    
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
        
     - name: Install dependencies
       run: npm ci --silent
     
     - name: Run Tests
       run: npm run test